export const NUMBER_OF_CARDS_IN_DECK = 42;

export const BREAKPOINTS = {
    xs: "max-width: 575.98px",
    sm: "max-width: 767.98px",
    md: "max-width: 991.98px",
    lg: "max-width: 1199.98px",
    xl: "min-width: 1200px"
}

export const COUNTRIES = {
    Afghanistan: { name: "Afghanistan", value: "afghanistan" },
    Alaska: { name: "Alaska", value: "alaska" },
    Alberta: { name: "Alberta", value: "alberta" },
    Argentina: { name: "Argentina", value: "argentina" },
    Brazil: { name: "Brazil", value: "Brazil" },
    Central_Africa: { name: "Central Africa", value: "central_africa" },
    Central_America: { name: "Central America", value: "central_america" },
    China: { name: "China", value: "china" },
    East_Africa: { name: "East Africa", value: "east_africa" },
    Eastern_Australia: { name: "Eastern Australia", value: "eastern_australia" },
    Eastern_Canada: { name: "Eastern Canada", value: "eastern_canada" },
    Eastern_United_States: { name: "Eastern United States", value: "eastern_united_states" },
    Egypt: { name: "Egypt", value: "egypt" },
    Great_Britain: { name: "Great Britain", value: "great_britain" },
    Greenland: { name: "Greenland", value: "greenland" },
    Iceland: { name: "Iceland", value: "iceland" },
    India: { name: "India", value: "india" },
    Indonesia: { name: "Indonesia", value: "indonesia" },
    Irkutsk: { name: "Irkutsk", value: "irkutsk" },
    Japan: { name: "Japan", value: "japan" },
    Kamchatka: { name: "Kamchatka", value: "kamchatka" },
    Madagascar: { name: "Madagascar", value: "madgascar" },
    Middle_East: { name: "Middle East", value: "middle_east" },
    Mongolia: { name: "Mongolia", value: "mongolia" },
    New_Guinea: { name: "New Guinea", value: "new_guinea" },
    North_Africa: { name: "North Africa", value: "north_africa" },
    Northern_Europe: { name: "Northern Europe", value: "northern_europe" },
    Northwest_Territory: { name: "Northwest Territory", value: "northwest_territory" },
    Ontario: { name: "Ontario", value: "ontario" },
    Peru: { name: "Peru", value: "peru" },
    Rusia: { name: "Rusia", value: "rusia" },
    Scandinavia: { name: "Scandinavia", value: "scandinavia" },
    Siberia: { name: "Siberia", value: "siberia" },
    South_Africa: { name: "South Africa", value: "south_africa" },
    Southeast_Asia: { name: "Southeast Asia", value: "southeast_asia" },
    Southern_Europe: { name: "Southern Europe", value: "southern_europe" },
    Ural: { name: "Ural", value: "ural" },
    Venezuela: { name: "Venezuela", value: "venezuela" },
    Western_Australia: { name: "Western Australia", value: "western_australia" },
    Western_Europe: { name: "Western Europe", value: "wstern_europe" },
    Western_United_States: { name: "Western United States", value: "western_united_states" },
    Yakutsk: { name: "Yakutsk", value: "yakutsk" },
};

export const TROOP_TYPES = {
    Infantry: { name: "INFANTRY", troopSize: 1 },
    Cavalry: { name: "CAVALRY", troopSize: 5 },
    Artillery: { name: "ARTILLERY", troopSize: 10 }
};

export const CARDS = [
    { country: COUNTRIES.Afghanistan.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Alaska.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Alberta.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Argentina.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Brazil.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Central_Africa.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Central_America.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.China.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.East_Africa.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Eastern_Australia.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Eastern_Canada.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Eastern_United_States.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Egypt.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Great_Britain.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Greenland.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Iceland.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.India.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Indonesia.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Irkutsk.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Japan.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Kamchatka.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Madagascar.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Middle_East.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Mongolia.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.New_Guinea.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.North_Africa.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Northern_Europe.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Northwest_Territory.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Ontario.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Peru.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Rusia.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Scandinavia.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Siberia.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.South_Africa.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Southeast_Asia.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Southern_Europe.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Ural.name, troop: TROOP_TYPES.Cavalry.name },
    { country: COUNTRIES.Venezuela.name, troop: TROOP_TYPES.Infantry.name },
    { country: COUNTRIES.Western_Australia.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Western_Europe.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Western_United_States.name, troop: TROOP_TYPES.Artillery.name },
    { country: COUNTRIES.Yakutsk.name, troop: TROOP_TYPES.Cavalry.name }
]

export const NEIGHBOURS = {
    indonesia: { neighbours: ["siam", "western_australia", "new_guinea"]},
    new_guinea: { neighbours: ["indonesia", "eastern_australia", "western_australia"]},
    
};